version: '3.5'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: teste
      MYSQL_USER: user_teste
      MYSQL_PASSWORD: usertest123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: